### PR TITLE
Provide a pop up if the OTA upgrade fails

### PR DESCRIPTION
**Pull request by BluemarkInnovations**
In this PR, a pop up is shown if the OTA upgrade via the web interface fails. 
For instance if the wrong file is uploaded. 

fail

### CODE REVIEW

**Comment by tridge** [comment]
i've been testing this by trying to load a fw with the wrong board ID and it still gives me success display, but doesn't update the fw

**Comment by BluemarkInnovations** [comment]
improved PR, solved a bug in the check_OTA_partition function.

**Comment by tridge** [comment]
@BluemarkInnovations thanks, I've fixed the PR to squash the commits, and have gone back to using a reference (no need to use a pointer for the board_id)

**Comment by BluemarkInnovations** [comment]
> @BluemarkInnovations thanks, I've fixed the PR to squash the commits, and have gone back to using a reference (no need to use a pointer for the board_id)

Thanks, I wasn't familiar with references in C.

**Pull request merged**
