### PR TITLE
re-enable BLE 2M

### PR DESCRIPTION
**Pull request by tridge**
needed for some older phones
NO MERGE: pending testing

### CODE REVIEW

**Comment by friissoren** [comment]
I don't believe this will be necessary. It should be possible to reach all phones with the legacy advertising style. 

I started yesterday looking at the details of the configurations but ran out of time (and probably won't have time today either). Hopefully by the end of the week I can come back to you with some suggestions.

**Comment by friissoren** [comment]
I think I managed to configure the BT4 Legacy and BT5 Long Range advertising correctly. [Draft changes here](https://github.com/ArduPilot/ArduRemoteID/compare/master...friissoren:ArduRemoteID:various_fixes).

The reason you are not getting any data through with the BT4 Legacy Advertising is because the full message pack will not fit. BT4 advertising can contain max 25 bytes, when the other header overhead is taken into account. This is the original reason why all drone ID data is split into max 25 bytes messages.

I will try to fix this when I find a spare moment. Cycling through the messages is needed for BT4.

**Comment by tridge** [comment]
@friissoren thanks for your help, much appreciated!

**Comment by BluemarkInnovations** [comment]
hopefully BLE issues have been fixed in this PR https://github.com/ArduPilot/ArduRemoteID/pull/25

**Comment by friissoren** [comment]
> hopefully BLE issues have been fixed in this PR #25

I agree. @tridge: I think you can discard this PR.

**Pull request closed without merging**
