### PR TITLE
use latest mavlink definitions for MAV_ODID_ARM_STATUS

### PR DESCRIPTION
**Pull request by BluemarkInnovations**
ArduRemoteID implementation for this PR https://github.com/ArduPilot/mavlink/pull/295

### CODE REVIEW

**Comment by BluemarkInnovations** [comment]
and raised in this PR https://github.com/ArduPilot/ArduRemoteID/issues/35

**Comment by tridge** [comment]
we need to first get an ArduPilot PR done to change the enums and update the submodule
note that these names make no difference to the code

**Comment by BluemarkInnovations** [comment]
> we need to first get an ArduPilot PR done to change the enums

See https://github.com/ArduPilot/mavlink/pull/295

> note that these names make no difference to the code

To my understanding if you change the ENUMs, also the magic byte in the message changes. If this is true, it is hard to use the current ArduRemoteID firmware with other flight controller software that use a different definition for this message.

**Comment by tridge** [comment]
i've fixed the PR to include the mavlink update

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
rebased and fixed build errors

**Pull request merged**
